function Indexs=selectIndexs(Items)
% Items={ '\\hl\nbidas' 'D:\das' '\\hl\2mccs' '\\hl\2MDAS' '\\hl\2adas'};
fontsize=12;
NumChannels=length(Items);
Rows=NumChannels+2;

hChannelSelect=figure('MenuBar','none','Tag','ChannelSelect','Resize','off','HitTest','off');%,...
scrsz = get(0,'ScreenSize');
scrsz=[10 40 (scrsz(3)-scrsz(1))*0.2 scrsz(4)-scrsz(2)-30];
scrsz=[10 40 fontsize*20 fontsize*Rows*2];
set(hChannelSelect,'Units','points','Position',scrsz);


Cols=2;
wstep=scrsz(3)/Cols;
hstep=scrsz(4)/Rows;
w=wstep/3;
h=hstep*0.85;
b=scrsz(2)-26;
l=6;




for i=1:NumChannels
    hCheckBox(i) = uicontrol('parent',                   hChannelSelect,...
        'Units',                    'points', ...
        'String',                  '', ...
        'BackgroundColor',                  'b', ...
        'Position',                 [l,b,w/2,h],...
        'HorizontalAlignment',      'left', ...
        'FontWeight',               'bold', ...
        'FontSize',                 fontsize,...
        'Style',                    'checkbox', ...
        'value',                    1, ...
        'Enable',                   'on', ...
        'visible',                   'on', ...
        'Tooltipstring',            'channels OK');
    l2=l+w/2;
    hChannel(i) = uicontrol('parent',                   hChannelSelect,...
        'Units',                    'points', ...
        'String',                   Items{i}, ...
        'Position',                 [l2,b,3*w,h],...
        'HorizontalAlignment',      'left', ...
        'FontWeight',               'bold', ...
        'FontSize',                 fontsize,...
        'Style',                    'edit', ...
        'Enable',                   'on', ...
        'Tooltipstring',            'channels OK');
    b=b+hstep;
end


hsetValue = uicontrol('parent',                   hChannelSelect,...
    'Units',                    'points', ...
    'String',                   'inv', ...
    'Position',                 [l,b,w/2,h],...
    'HorizontalAlignment',      'left', ...
    'FontWeight',               'bold', ...
    'FontSize',                 fontsize,...
    'Style',                    'pushbutton', ...
    'Enable',                   'on', ...
    'callback',                 {@mysetValue},...
    'Tooltipstring',            'current Server');
    l2=l+w/2;
hSetIndexs = uicontrol('parent',                   hChannelSelect,...
    'Units',                    'points', ...
    'String',                   'OK', ...
    'Position',                 [l2,b,3*w,h],...
    'HorizontalAlignment',      'left', ...
    'FontWeight',               'bold', ...
    'FontSize',                 fontsize,...
    'Style',                    'pushbutton', ...
    'Enable',                   'on', ...
    'callback',                 {@mySelect},...
    'Tooltipstring',            'current Server');
b=b+hstep;



% setappdata(0,'hCheckBox',hCheckBox)
setappdata(0,'hCheckBox',hCheckBox)
setappdata(0,'hChannel',hChannel)
uiwait(hChannelSelect)

% get and set the Indexs

Indexs=getappdata(0,'Indexs');

Indexs=logical(Indexs);




function mysetValue(hObject, eventdata, index)
hCheckBox=getappdata(0,'hCheckBox');

for i=1:length(hCheckBox)
    value=get(hCheckBox(i),'value');
    if value
        set(hCheckBox(i),'value',0)
    else
        set(hCheckBox(i),'value',1)
    end
end




function mySelect(hObject, eventdata, index)
hCheckBox=getappdata(0,'hCheckBox');
for i=1:length(hCheckBox)
    Indexs(i)=get(hCheckBox(i),'value');
end
setappdata(0,'Indexs',Indexs);
delete(get(hObject,'parent'))

